version: '3.8'

services:
  nlp:
    build:
      context: .devcontainer
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
    command: jupyter lab --ip=0.0.0.0 --port=5000 --no-browser --allow-root
